services:
  - type: web
    name: ai-itinerary-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: PORT
        value: 10000