services:
  - type: web
    name: ai-itinerary-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HF_TOKEN
        sync: false